# variable file for bigip-a
address: 10.1.1.7
ansible_host: 10.1.1.7 
#ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}" 
#ansible_ssh_user: "{{ vault_ansible_ssh_user }}" 
selfAddrExt: 10.1.20.20
selfAddrInt: 10.1.30.20
